language: en
pipeline:
  - name: SpacyNLP
    model: en_ner_demo_replace
  - name: SpacyTokenizer
  - name: RegexFeaturizer
    pooling: mean
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    dimensions: ["PERSON", "PRODUCT"]
  - name: RegexEntityExtractor
    case_sensitive: False
    use_lookup_tables: True
    use_regexes: True
    "use_word_boundaries": True
    dimensions: ["caller_name", "company_name"]